title: Blog Saya
description: Catatan belajar dan eksperimen
author: Alph

# URL (penting!)
baseurl: "/private-blog" # kalau pakai repo (bukan domain utama)
url: "https://alphocado.github.io"

# Markdown engine
markdown: kramdown

# Format permalink (URL artikel)
permalink: /:year/:month/:day/:title/

# Timezone (optional)
timezone: Asia/Makassar

# Exclude file dari build
exclude:
  - gui_app.py
  - README.md
